const mysql = require('mysql') // modulo para bbdd mysql
const { promisify } = require('util')

const pool = mysql.createPool({
  host: 'localhost',
  user: 'NormalUser',
  password: 'NormalUser',
  database: 'prueba',
})
pool.query = promisify(pool.query)

module.exports = pool
/*
CREATE DATABASE PRUEBA;
USE PRUEBA;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(200),
    PERMISS VARCHAR(20)
);
INSERT INTO USER(USERNAME,PASSWORD,PERMISS)
VALUES("amy","$2b$10$B3aozsB.Dw1gFitnm8k3EulfBXrGikAxFMVrYJxHFHR6CjbZanZ0a","ADMIN");

DROP TABLE IF EXISTS REPCONFIG;
CREATE TABLE REPCONFIG(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    TOKEN VARCHAR(200) NOT NULL,
    PROJECT INT(2) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    PROGRAMED_DATE DATETIME,
    CREATED_USER_ID BIGINT UNSIGNED NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NAME VARCHAR(50) NOT NULL,
    FOREIGN KEY(CREATED_USER_ID) REFERENCES USER(ID)
);

INSERT INTO REPCONFIG(LOGIN,TOKEN,PROJECT,TYPE,CREATED_USER_ID,NAME)
VALUES("gps-plan","token",7,"organization",2,"mock room")

DROP TABLE IF EXISTS USER_SALA;
CREATE TABLE USER_SALA(
    USER_ID BIGINT UNSIGNED,
    REPCONFIG_ID BIGINT UNSIGNED,
    PRIMARY KEY(USER_ID,REPCONFIG_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (REPCONFIG_ID) REFERENCES REPCONFIG(ID)
)

DROP IF EXISTS ISSUE_SALA;
CREATE TABLE ISSUE_SALA(
    ISSUE_ID INT(4) NOT NULL,
);
*/

// amy password =  $2b$10$B3aozsB.Dw1gFitnm8k3EulfBXrGikAxFMVrYJxHFHR6CjbZanZ0a